name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  deploy_zip:
      runs-on: ubuntu-latest
      steps:
        - uses: papeloto/action-zip@v1
          with: 
            files: deploy/aws/main.py
            dest: main.zip
        - name: default deploy
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-east-1
            function_name: github-action-test
            zip_file: main.zip

