name: deploy to lambda
on: [push]
jobs:
  deploy_zip:
      name: deploy lambda function
      runs-on: ubuntu-latest
      steps:
        - name: Build binary
          run: |
            echo $PWD
        - name: default deploy
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-east-1
            function_name: test_main
            zip_file: main.zip